### PR TITLE
Implement *put* and IO management for Windows

### PR DESCRIPTION
**Pull request by robinlinden**
@johnor What do you think? What we have to implement for each platform is __std* and _Write.

### CODE REVIEW

**Comment by robinlinden** [comment]
Yeah, definitely. You're right. 😁  More tests incoming.

**Comment by robinlinden** [comment]
Implemented your suggestion, @johnor. Now the tests actually test things. 😁

```
robin@thing MINGW64 /d/projects/stdlib2 (puts)
$ ./build/test/test_putc.exe
abcdefghijklmnopqrstuvwxy
robin@thing MINGW64 /d/projects/stdlib2 (puts)
$ ./build/test/test_puts.exe
domo arigato mr robotto

robin@thing MINGW64 /d/projects/stdlib2 (puts)
$ ./build/test/test_fputc.exe
ABCDEFGHIJKLMNOPQRSTUVWXY
```

**Comment by johnor** [comment]
Good! What do we do with the failing CI? Should we just ignore it for now, or only enable tests on the platforms we know they should work?

**Comment by robinlinden** [comment]
I added stubs and marked the tests as WILL FAIL, so I guess this is ready for review. :P

**Pull request merged**
